name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "kiaa-pku.cn"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "kiaa-pku.cn"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.kiaa-pku.cn", custom_domain = true },
  { pattern = "quay.kiaa-pku.cn", custom_domain = true },
  { pattern = "gcr.kiaa-pku.cn", custom_domain = true },
  { pattern = "k8s-gcr.kiaa-pku.cn", custom_domain = true },
  { pattern = "k8s.kiaa-pku.cn", custom_domain = true },
  { pattern = "ghcr.kiaa-pku.cn", custom_domain = true },
  { pattern = "cloudsmith.kiaa-pku.cn", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.kiaa-pku.cn", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
